# Generated by Django 4.0 on 2021-12-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servermanagement',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
