# Generated by Django 4.0 on 2021-12-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_remove_servermanagement_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servermanagement',
            name='occupied_time',
            field=models.DateTimeField(null=True),
        ),
    ]
