# Generated by Django 4.0 on 2021-12-09 10:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_alter_serverreservation_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverreservation',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 9, 12, 30, 46, 192207, tzinfo=utc)),
        ),
    ]
