# Generated by Django 4.0 on 2021-12-10 07:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_alter_serverreservation_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='servermanagement',
            name='ip_addr',
            field=models.CharField(default='0.0.0.0', max_length=255),
        ),
        migrations.AlterField(
            model_name='servermanagement',
            name='processor',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='serverreservation',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 10, 9, 19, 5, 44192, tzinfo=utc)),
        ),
    ]
