# Generated by Django 4.0 on 2021-12-10 07:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_servermanagement_ip_addr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servermanagement',
            name='server_name',
            field=models.CharField(default='Server ', max_length=255),
        ),
        migrations.AlterField(
            model_name='serverreservation',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 10, 9, 54, 47, 94422, tzinfo=utc)),
        ),
        migrations.AddConstraint(
            model_name='servermanagement',
            constraint=models.CheckConstraint(check=models.Q(('server_name__gte', 'Server')), name='server name'),
        ),
    ]
