# Generated by Django 4.0 on 2021-12-10 08:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_alter_servermanagement_server_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servermanagement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='serverreservation',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 10, 10, 1, 41, 174354, tzinfo=utc)),
        ),
    ]
