# Generated by Django 3.2.5 on 2021-12-14 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_alter_serverreservation_end_time_cpuusage'),
        ('server', '0014_alter_serverreservation_end_time'),
    ]

    operations = [
    ]
