# Generated by Django 4.0 on 2021-12-17 12:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_merge_20211214_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverreservation',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 17, 14, 24, 14, 970457, tzinfo=utc)),
        ),
    ]
